* Favourite projects:

** Clustering large number of time series.
*** Professor: Andrés Alonso (andres.alonso@uc3m.es) and Daniel Peña (daniel.pena@uc3m.es).
*** Summary: 
    The dynamic factor model is a well established modeling strategy when we face a large number of time series which makes it impossible to use standard multivariate techniques such as VARIMA models. Those time series could share some common factor but also the factors can have a group structure. Ando and Bai (2016) propose an iterative procedure for estimating a factor model with grouped factor structures. The starting step of the procedure relies on k-means algorithm and Euclidean metric on the original time series. It is known that Euclidean distance does not take into account the dependence among the individuals (time series in our case). In this project, we will consider other algorithms and metrics as starting step of the Ando and Bai’s procedure. We will evaluate the forecasting performance of the original and the proposed modification. The evaluation will consist of an extensive simulation study and its application to time series of the electricity market.
*** References:
    Ando, T. and Bai, J. (2016) Clustering huge number of financial time series: A panel data approach with high-dimensional predictors and factor structures. To appear at JASA. Available at: http://dx.doi.org/10.1080/01621459.2016.1195743

** Short-term air pollution forecasting in Madrid
*** Professor: Francisco Javier Nogales Martín (fjnm@est-econ.uc3m.es) and Carlos Ruíz Mora (caruizm@est-econ.uc3m.es).
*** Summary: 
    Develop an automatic tool to predict hourly Madrid air-pollution on a daily basis, using time series and machine learning tools. The tool must be able to connect daily with the data bases, perform the forecasts, compute the associated errors, and generate a convenient output (ideally on a web server).
*** Source: Open Data Madrid.

** Machine learning for time series forecasting
*** Profesor: Carlo Sguera (csguera@est-econ.uc3m.es).
*** Summary: 
    Machine learning models are used especially in classification and regression problems. Recently, machine learning models have established themselves as contenders to classical statistical models in the time series forecasting community (see De Gooijer and Hyndman 2006 for classical time series forecasting, and Ahmed et al. 2010 and Bontempi et al. 2013 for machine learning time series forecasting). The goal of this Master’s Thesis is dual: first, it will survey the recent literature in the domain of machine learning techniques used to forecast time series; second, it will present a comparison study for the classical statistical models and the major machine learning models for time series forecasting. M3 competition data (2008) is an option to conduct the comparison study.
*** References:
    Ahmed, N. K., Atiya, A. F., Gayar, N. E., and El-Shishiny, H. (2010). 
    An empirical comparison of machine learning models for time series forecasting. Econometric Reviews, 29(5-6):594–621. Bontempi, G., Taieb, S. B., and Le Borgne, Y.-A. (2013). 
    Machine learning strategies for time series forecasting. In Business Intelligence, pages 62–77. Springer. De Gooijer, J. G. and Hyndman, R. J. (2006). 
    25 years of time series forecasting. International journal of forecasting, 22(3):443–473. 
    M3 Competition (2008). http://forecasters.org/resources/time-series-data/m3-competition/.

** Hourly electricity consumption in Smart grids
*** Professor: Francisco Javier Nogales Martín (fjnm@est-econ.uc3m.es) and Carlos Ruíz Mora (caruizm@est-econ.uc3m.es).
*** Summary: 
    Develop an analytical tool to predict hourly electricity consumption on a daily basis, using time series and machine learning tools. The tool must be able to clean automatically the data, perform the forecasts, compute the associated errors, and generate a convenient output.
*** Source: EnerNOC.

** Multivariate electricity price forecasting in Europe
*** Professor: Francisco Javier Nogales Martín (fjnm@est-econ.uc3m.es) and Carlos Ruíz Mora (caruizm@est-econ.uc3m.es).
*** Summary: 
    Develop an automatic tool to predict (short/medium) electricity prices in several European countries on a daily basis, using time series and machine learning tools. The tool must be able to connect daily with the data bases, perform the forecasts, compute the associated errors, and generate a convenient output (ideally on a web server).
*** Source: Epex, Nordpool, Gme, Tge and Omie.

** Improved automatic text simplification by machine learning techniques.
*** Professor: Jorge Luis Morato Lara (jmorato@inf.uc3m.es).
*** Summary: 
    Text simplification is a classical task in Natural Language Processing. Unfortunately, most algorithms show poor performance. The student should propose a combination of parameters and tools that presents a significant improvement in the State-of-the-Art. Specifically, the student should test the algorithms already implemented in the LEXenstein simplification platform. A background in Python and R is advisable.

** Big Data Analytics for Blockchain Management in the Energy Market.
*** Professor: Juan Miguel Gómez Berbís (juanmiguel.gomez@uc3m.es).
*** Summary: 
    Using Cassandra to store Blockchain and creating an energy market use case scenario.

** Short-term traffic forecasting in Madrid
*** Professor: Francisco Javier Nogales Martín (fjnm@est-econ.uc3m.es) and Carlos Ruíz Mora (caruizm@est-econ.uc3m.es).
*** Summary: 
    Develop an automatic tool to predict hourly Madrid traffic on a daily basis, using time series and machine learning tools. The tool must be able to connect daily with the data bases, perform the forecasts, compute the associated errors, and generate a convenient output (ideally on a web server).
*** Source: Open Data Madrid.

** Forecasting Spanish electricity demand by technology and its relation with pool price
*** Professor: Francisco Javier Nogales Martín (fjnm@est-econ.uc3m.es) and Carlos Ruíz Mora (caruizm@est-econ.uc3m.es).
*** Summary: 
    Develop an automatic tool to predict (short/medium) electricity demand in Spain by technology on a daily basis, using time series and machine learning tools. The tool must be able to connect daily with the data bases, perform the forecasts, compute the associated errors, and generate a convenient output (ideally on a web server).
*** Source: Esios and Omie.

** Spanish electricity price forecasting
*** Professor: Francisco Javier Nogales Martín (fjnm@est-econ.uc3m.es) and Carlos Ruíz Mora (caruizm@est-econ.uc3m.es).
*** Summary: 
    Automatic tool to predict (short/medium/large) electricity prices in Spain on a daily basis, using time series and machine learning tools. The tool must be able to connect daily with the data bases, perform the forecasts, compute the associated errors, and generate a convenient output (ideally on a web server).
*** Source: Esios and Omie.
